# Generated by Django 2.2.1 on 2019-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
