# Generated by Django 2.2.1 on 2019-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20190602_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='word',
            field=models.TextField(max_length=20),
        ),
    ]
